cache: C:\TEMP\railedge_cache\
server: L10349
port: 8000
username: nedenckl
password: Lor2m6789!
max_hits_to_cache: 5 # do not download more than this many hits
max_images_to_cache: 1000 # do not download more than than many images

# If keep_prev is true, will adjust the 'edge' box slightly to match up with
#   the new image
auto_detect_edges_from_previous: true
auto_detect_edges_from_previous_label: edge # name of the label to edit
manual_label_every_n: 3 # skip forward this many images every time next is hit. Set to 1 for regular behavior

auto_save: true
display_label_popup: true
instance_label_auto_increment: true
store_data: false
keep_prev: true
logger_level: info

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

# main
hit_dock:
  show: true
  closable: true
  movable: true
  floatable: true
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

epsilon: 10.0

shortcuts:
  close: Ctrl+W
  open: Ctrl+o
  open_dir: Ctrl+U
  quit: Ctrl+p
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [r, Ctrl+Shift+D]
  open_prev: [f, Ctrl+Shift+A]

  zoom_in: [e, Ctrl++,Ctrl+=]
  zoom_out: [q, Ctrl+-]
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+l
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
  toggle_keep_prev_mode: Ctrl+P
